### ISSUE TITLE
Deprecated selector in `dropkick-dark-syntax\index.less`

### ISSUE THREAD

**Issue by TheSolly** [frodo4fingers/dropkick-syntax#1]
In `dropkick-dark-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `.comment` => `.syntax--comment`

* `.string.quoted` => `.syntax--string.syntax--quoted`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant.language` => `.syntax--constant.syntax--language`

* `.constant.character,
.constant.other` => `.syntax--constant.syntax--character,
.syntax--constant.syntax--other`

* `.variable` => `.syntax--variable`

* `.keyword` => `.syntax--keyword`

* `.storage` => `.syntax--storage`

* `.entity.name.class,
.entity.name.type,
.entity.name.function` => `.syntax--entity.syntax--name.syntax--class,
.syntax--entity.syntax--name.syntax--type,
.syntax--entity.syntax--name.syn

**Comment by frodo4fingers** [comment]
argh.. yes. you are totally right about that and i forgot. i will see that i can update the syntax this weekend. i negleted this color theme in favor of [this](https://atom.io/themes/nordkind-dark-syntax) one. I'm on it :-)

**Comment by frodo4fingers** [comment]
is updated and should work.
thank you
